import type { AgentDef } from "@/types/index";

export const LIBRARY_AGENTS: AgentDef[] = [
  // USER STORIES PIPELINE
  { id: "domain-analyst", name: "Domain Discovery Agent", role: "Market & Persona Research", description: "Researches your idea, identifies the target market, users, and key personas.", pipeline_type: "user_stories", order: 1, icon: "🔍", estimated_duration: 5, has_skill: true },
  { id: "epic-architect", name: "Backlog Architecture Agent", role: "Epic & Story Composition", description: "Writes product epics and detailed user stories with clear acceptance criteria.", pipeline_type: "user_stories", order: 2, icon: "🏗️", estimated_duration: 10, has_skill: true },
  { id: "story-estimator", name: "Estimation Agent", role: "Effort & Dependency Mapping", description: "Estimates effort for each story and maps out which tasks depend on others.", pipeline_type: "user_stories", order: 3, icon: "🎯", estimated_duration: 5, has_skill: true },
  { id: "nfr-specialist", name: "Quality Requirements Agent", role: "Performance, Security & Compliance", description: "Adds quality requirements covering performance, security, and accessibility.", pipeline_type: "user_stories", order: 4, icon: "⚡", estimated_duration: 5, has_skill: true },
  { id: "backlog-reviewer", name: "Quality Review Agent", role: "Backlog Validation & Gap Analysis", description: "Reviews all stories for completeness, gaps, and quality before finalizing.", pipeline_type: "user_stories", order: 5, icon: "✅", estimated_duration: 4, has_skill: true },
  { id: "backlog-compiler", name: "Delivery Compilation Agent", role: "Final Backlog Synthesis", description: "Compiles all stories into a clean, structured document ready for your team.", pipeline_type: "user_stories", order: 6, icon: "📦", estimated_duration: 6, has_skill: true },

  // PPT PIPELINE
  { id: "ppt-content-strategist", name: "Content Strategy Agent", role: "Narrative & Messaging", description: "Plans the story, key messages, and content for each slide in your presentation.", pipeline_type: "ppt", order: 1, icon: "🎯", estimated_duration: 8, has_skill: true },
  { id: "ppt-slide-architect", name: "Visual Design Agent", role: "Slide Layout & Composition", description: "Designs the visual layout, structure, and look of each slide.", pipeline_type: "ppt", order: 2, icon: "🏗️", estimated_duration: 10, has_skill: true },
  { id: "ppt-code-generator", name: "Slide Generation Agent", role: "Presentation Engineering", description: "Builds the complete presentation with all slides, charts, and visual elements.", pipeline_type: "ppt", order: 3, icon: "💻", estimated_duration: 15, has_skill: true },
  { id: "ppt-assembler", name: "Deck Assembly Agent", role: "Final Deck Compilation", description: "Packages the final presentation with preview and download ready for sharing.", pipeline_type: "ppt", order: 4, icon: "📦", estimated_duration: 12, has_skill: true },

  // PROTOTYPE PIPELINE
  { id: "requirements-analyst", name: "Experience Discovery Agent", role: "UX Flows & Navigation", description: "Plans the pages, navigation flows, and user experience for your prototype.", pipeline_type: "prototype", order: 1, icon: "📋", estimated_duration: 6, has_skill: true },
  { id: "html-prototype-builder", name: "Prototype Generation Agent", role: "Interactive HTML Engineering", description: "Builds a complete interactive prototype with all pages and navigation.", pipeline_type: "prototype", order: 2, icon: "🖥️", estimated_duration: 15, has_skill: true },
  { id: "prototype-polisher", name: "Design Refinement Agent", role: "Visual & Interaction Quality", description: "Reviews and refines the prototype for visual quality and smooth interactions.", pipeline_type: "prototype", order: 3, icon: "✨", estimated_duration: 8, has_skill: true },
  { id: "prototype-finalizer", name: "Delivery Validation Agent", role: "Final Quality Gate", description: "Validates and packages the final prototype ready for review and handoff.", pipeline_type: "prototype", order: 4, icon: "📦", estimated_duration: 5, has_skill: true },

  // APP BUILDER PIPELINE — 15-agent SDLC
  { id: "material-analyzer", name: "Architecture Agent", role: "Solution & System Design", description: "Analyzes your requirements and designs the complete application architecture.", pipeline_type: "app_builder", order: 1, icon: "📋", estimated_duration: 6, has_skill: false },
  { id: "app-user-stories", name: "User Stories Agent", role: "Requirements & Acceptance Criteria", description: "Translates the architecture into epics, user stories, and Gherkin acceptance criteria the team can pick up as deliverable work.", pipeline_type: "app_builder", order: 2, icon: "📝", estimated_duration: 9, has_skill: true },
  { id: "app-system-design", name: "System Design Agent", role: "Detailed Architecture & Decomposition", description: "Detailed component decomposition, sync/async boundaries, state ownership, deployment topology, and ADRs.", pipeline_type: "app_builder", order: 3, icon: "🏗️", estimated_duration: 10, has_skill: true },
  { id: "app-security-architecture", name: "Security Architecture Agent", role: "Threat Modelling & Security Controls", description: "STRIDE threat model, identity/IAM design, encryption, secrets, WAF, and security gates for the application.", pipeline_type: "app_builder", order: 4, icon: "🛡️", estimated_duration: 9, has_skill: true },
  { id: "app-ux-design", name: "UX & UI Design Agent", role: "User Journeys, Wireframes & Design System", description: "Information architecture, wireframes, design tokens, component library, accessibility plan, and error/loading states.", pipeline_type: "app_builder", order: 5, icon: "🎨", estimated_duration: 9, has_skill: true },
  { id: "app-api-design", name: "API Contract Agent", role: "REST/GraphQL Contracts & OpenAPI", description: "Endpoint contracts, error envelopes, idempotency rules, async event contracts, versioning policy, and the OpenAPI 3.1 document.", pipeline_type: "app_builder", order: 6, icon: "🔌", estimated_duration: 8, has_skill: true },
  { id: "app-database-design", name: "Data Model Agent", role: "Schema, Indexes & Migrations", description: "Entity model, DDL, indexing strategy, migration tooling, PII classification, backup/recovery targets, and query budgets.", pipeline_type: "app_builder", order: 7, icon: "🗄️", estimated_duration: 8, has_skill: true },
  { id: "app-code-generator", name: "Code Generation Agent", role: "Full-Stack Code Generation", description: "Generates complete frontend and backend code for your application — controllers, services, models, pages, components.", pipeline_type: "app_builder", order: 8, icon: "💻", estimated_duration: 15, has_skill: false },
  { id: "app-feature-implementation", name: "Feature Implementation Agent", role: "Business Logic per User Story", description: "Fleshes out the user stories' business logic in the generated codebase — route handlers, services, integrations, and feature flags.", pipeline_type: "app_builder", order: 9, icon: "⚙️", estimated_duration: 14, has_skill: true },
  { id: "app-infra-generator", name: "Infrastructure Agent", role: "Deployment & Platform", description: "Sets up deployment configuration, tests, and infrastructure for your app.", pipeline_type: "app_builder", order: 10, icon: "🚀", estimated_duration: 8, has_skill: false },
  { id: "app-code-compliance", name: "Code Compliance Agent", role: "Static Analysis, Linting & Licensing", description: "SAST/SCA tooling, SonarQube quality gates, language-specific lint config, license policy, and pre-commit/CI gates.", pipeline_type: "app_builder", order: 11, icon: "🧪", estimated_duration: 8, has_skill: true },
  { id: "app-test-implementation", name: "Test Implementation Agent", role: "Unit, Integration & Contract Test Code", description: "Writes the test code (JUnit/xUnit/Jest/Pact/Playwright) that proves the user stories' acceptance criteria.", pipeline_type: "app_builder", order: 12, icon: "🧬", estimated_duration: 12, has_skill: true },
  { id: "app-test-compliance", name: "Test Compliance Agent", role: "Test Strategy & Coverage Gates", description: "Test pyramid, coverage gates, compliance test mapping (PCI/GDPR/SOC 2), performance and chaos plans.", pipeline_type: "app_builder", order: 13, icon: "🎯", estimated_duration: 8, has_skill: true },
  { id: "app-devops", name: "DevOps Agent", role: "Build, Deploy, Operate & Quality Gates", description: "Branching model, CI/CD pipeline-as-code, environment promotion, OIDC secrets, DORA-metric observability, and developer-experience tooling.", pipeline_type: "app_builder", order: 14, icon: "🚦", estimated_duration: 9, has_skill: true },
  { id: "app-sdlc-governance", name: "SDLC Governance & Handover Agent", role: "ADRs, Runbooks, SLOs & Operations Handover", description: "Architecture Decision Records, runbooks, SLOs/SLIs, dashboards, compliance evidence matrix, and operations handover.", pipeline_type: "app_builder", order: 15, icon: "📚", estimated_duration: 9, has_skill: true },

  // MIGRATION: MULESOFT → SPRING BOOT MICROSERVICES ON AWS
  { id: "mulesoft-inventory", name: "Mulesoft Asset Inventory Agent", role: "Mule App Discovery & Cataloguing", description: "Catalogues your Mulesoft estate — flows, connectors, DataWeave transforms, and migration risk hotspots.", pipeline_type: "mulesoft_to_springboot", order: 1, icon: "📋", estimated_duration: 8, has_skill: true },
  { id: "mulesoft-user-stories", name: "Migration User Stories Agent", role: "Requirements & Acceptance Criteria", description: "Turns the inventory into epics, user stories, and Gherkin acceptance criteria for the migrated capabilities.", pipeline_type: "mulesoft_to_springboot", order: 2, icon: "📝", estimated_duration: 9, has_skill: true },
  { id: "mulesoft-decomposition", name: "Bounded Context Decomposition Agent", role: "Domain Modelling & Service Boundaries", description: "Proposes the Spring Boot microservice split with bounded contexts and service topology.", pipeline_type: "mulesoft_to_springboot", order: 3, icon: "🧩", estimated_duration: 10, has_skill: true },
  { id: "mulesoft-security-architecture", name: "Security Architecture Agent", role: "Threat Modelling & Security Controls", description: "STRIDE threat model, IAM/access design, encryption, secrets, WAF, and security gates for the target AWS architecture.", pipeline_type: "mulesoft_to_springboot", order: 4, icon: "🛡️", estimated_duration: 9, has_skill: true },
  { id: "mulesoft-springboot-scaffold", name: "Spring Boot Scaffold Agent", role: "Java Microservice Project Scaffolding", description: "Generates a commit-ready Spring Boot 3 scaffold for each microservice.", pipeline_type: "mulesoft_to_springboot", order: 5, icon: "☕", estimated_duration: 14, has_skill: true },
  { id: "mulesoft-feature-coding", name: "Feature Implementation Agent", role: "Business Logic & Feature Code", description: "Implements the user stories' business logic in the Spring Boot services — controllers, services, persistence, integrations.", pipeline_type: "mulesoft_to_springboot", order: 6, icon: "⚙️", estimated_duration: 14, has_skill: true },
  { id: "mulesoft-dataweave-translator", name: "DataWeave to Java Mapping Agent", role: "Transformation Logic Migration", description: "Translates DataWeave scripts into MapStruct or hand-written Java mappers with unit tests.", pipeline_type: "mulesoft_to_springboot", order: 7, icon: "🔄", estimated_duration: 10, has_skill: true },
  { id: "mulesoft-aws-infra", name: "AWS Landing Zone Agent", role: "Target Infrastructure on AWS", description: "Generates Terraform for ECS Fargate, RDS, SQS/SNS, ALB, and per-service IAM roles.", pipeline_type: "mulesoft_to_springboot", order: 8, icon: "☁️", estimated_duration: 12, has_skill: true },
  { id: "mulesoft-code-compliance", name: "Code Compliance Agent", role: "Static Analysis, Linting & Licensing", description: "SAST/SCA tooling, SonarQube quality gates, Checkstyle/SpotBugs/PMD config, license policy, and pre-commit/CI gates.", pipeline_type: "mulesoft_to_springboot", order: 9, icon: "🧪", estimated_duration: 8, has_skill: true },
  { id: "mulesoft-test-implementation", name: "Test Implementation Agent", role: "Unit, Integration & Contract Test Code", description: "Writes the JUnit 5 + Testcontainers + Spring Cloud Contract test code that proves the acceptance criteria.", pipeline_type: "mulesoft_to_springboot", order: 10, icon: "🧬", estimated_duration: 12, has_skill: true },
  { id: "mulesoft-test-compliance", name: "Test Compliance Agent", role: "Test Strategy & Coverage Gates", description: "Test pyramid, coverage gates, compliance test mapping (PCI/GDPR/SOC 2), perf & chaos plans.", pipeline_type: "mulesoft_to_springboot", order: 11, icon: "🎯", estimated_duration: 8, has_skill: true },
  { id: "mulesoft-validation", name: "Migration Validation Agent", role: "Parallel-Run & Cutover Gates", description: "Designs the parallel-run harness against the legacy Mule app, cutover gates, and rollback runbook.", pipeline_type: "mulesoft_to_springboot", order: 12, icon: "✅", estimated_duration: 8, has_skill: true },
  { id: "mulesoft-sdlc-governance", name: "SDLC Governance & Handover Agent", role: "ADRs, Runbooks, SLOs & Operations Handover", description: "Architecture Decision Records, runbooks, SLOs/SLIs, dashboards, compliance evidence matrix, and operations handover.", pipeline_type: "mulesoft_to_springboot", order: 13, icon: "📚", estimated_duration: 9, has_skill: true },

  // MIGRATION: .NET FRAMEWORK → AZURE (AI-augmented)
  { id: "dotnet-inventory", name: ".NET Solution Inventory Agent", role: "Legacy App Discovery & Cataloguing", description: "Catalogues your .NET estate — projects, frameworks, NuGet deps, auth model, and modernisation risk hotspots.", pipeline_type: "dotnet_to_azure", order: 1, icon: "📋", estimated_duration: 8, has_skill: true },
  { id: "dotnet-user-stories", name: "Migration User Stories Agent", role: "Requirements & Acceptance Criteria", description: "Turns the inventory into epics, user stories, and Gherkin acceptance criteria for the migrated capabilities.", pipeline_type: "dotnet_to_azure", order: 2, icon: "📝", estimated_duration: 9, has_skill: true },
  { id: "dotnet-azure-target-mapping", name: "Azure Target Mapping Agent", role: "Azure Service Recommendation", description: "Maps each .NET project to the right Azure service (App Service, AKS, Functions, SQL) with effort estimates.", pipeline_type: "dotnet_to_azure", order: 3, icon: "🎯", estimated_duration: 8, has_skill: true },
  { id: "dotnet-security-architecture", name: "Security Architecture Agent", role: "Threat Modelling & Security Controls", description: "STRIDE threat model, Entra ID/Key Vault design, encryption, WAF, and security gates for the target Azure architecture.", pipeline_type: "dotnet_to_azure", order: 4, icon: "🛡️", estimated_duration: 9, has_skill: true },
  { id: "dotnet-modernization", name: ".NET Core Modernisation Agent", role: ".NET Framework → .NET 8 Code Conversion", description: "Translates legacy .NET Framework projects to .NET 8 with breaking-change fixes and async-by-default.", pipeline_type: "dotnet_to_azure", order: 5, icon: "🔧", estimated_duration: 14, has_skill: true },
  { id: "dotnet-feature-coding", name: "Feature Implementation Agent", role: "Business Logic & Feature Code", description: "Implements the user stories' business logic in the modernised .NET 8 services — controllers, services, persistence, integrations.", pipeline_type: "dotnet_to_azure", order: 6, icon: "⚙️", estimated_duration: 14, has_skill: true },
  { id: "dotnet-azure-bicep", name: "Azure Bicep Provisioning Agent", role: "Azure Infrastructure as Code", description: "Generates Bicep modules for App Service, Functions, Azure SQL, Service Bus, networking, and observability.", pipeline_type: "dotnet_to_azure", order: 7, icon: "☁️", estimated_duration: 12, has_skill: true },
  { id: "dotnet-azure-ai", name: "Azure AI Integration Agent", role: "Cognitive & Generative AI Augmentation", description: "Identifies where Azure OpenAI / Document Intelligence / AI Search add measurable value and produces the C# integration code.", pipeline_type: "dotnet_to_azure", order: 8, icon: "🧠", estimated_duration: 10, has_skill: true },
  { id: "dotnet-code-compliance", name: "Code Compliance Agent", role: "Static Analysis, Linting & Licensing", description: "SAST/SCA tooling, SonarQube quality gates, Roslyn analyzers, .editorconfig, license policy, and pre-commit/CI gates.", pipeline_type: "dotnet_to_azure", order: 9, icon: "🧪", estimated_duration: 8, has_skill: true },
  { id: "dotnet-test-implementation", name: "Test Implementation Agent", role: "Unit, Integration & Contract Test Code", description: "Writes the xUnit + FluentAssertions + Testcontainers + Pact test code that proves the acceptance criteria.", pipeline_type: "dotnet_to_azure", order: 10, icon: "🧬", estimated_duration: 12, has_skill: true },
  { id: "dotnet-test-compliance", name: "Test Compliance Agent", role: "Test Strategy & Coverage Gates", description: "Test pyramid, coverage gates, compliance test mapping (PCI/GDPR/SOC 2), perf & chaos plans.", pipeline_type: "dotnet_to_azure", order: 11, icon: "🎯", estimated_duration: 8, has_skill: true },
  { id: "dotnet-validation", name: "Migration Validation Agent", role: "Behaviour Parity & Cutover Gates", description: "Designs parity tests, shadow-traffic config, Application Insights KQL gates, and the rollback drill.", pipeline_type: "dotnet_to_azure", order: 12, icon: "✅", estimated_duration: 8, has_skill: true },
  { id: "dotnet-sdlc-governance", name: "SDLC Governance & Handover Agent", role: "ADRs, Runbooks, SLOs & Operations Handover", description: "Architecture Decision Records, runbooks, SLOs/SLIs, dashboards, compliance evidence matrix, and operations handover.", pipeline_type: "dotnet_to_azure", order: 13, icon: "📚", estimated_duration: 9, has_skill: true },
];

export const CUSTOM_AGENTS: AgentDef[] = [
  { id: "market-research-agent", name: "Market Research Agent", role: "Competitive & Industry Analysis", description: "Analyzes your market, competitors, and industry trends to size the opportunity.", pipeline_type: "custom", order: 1, icon: "📈", estimated_duration: 6, has_skill: true },
  { id: "swot-analyst", name: "Strategy Analysis Agent", role: "SWOT & Strategic Positioning", description: "Identifies your strengths, weaknesses, opportunities, and threats with clear actions.", pipeline_type: "custom", order: 2, icon: "🎯", estimated_duration: 5, has_skill: true },
  { id: "roadmap-planner", name: "Roadmap Planning Agent", role: "Phased Delivery Strategy", description: "Builds a phased product roadmap with milestones, priorities, and timelines.", pipeline_type: "custom", order: 3, icon: "🗓️", estimated_duration: 6, has_skill: true },
  { id: "security-auditor", name: "Security Audit Agent", role: "Risk Assessment & Mitigation", description: "Reviews your product for security risks and provides a prioritized action plan.", pipeline_type: "custom", order: 4, icon: "🛡️", estimated_duration: 5, has_skill: true },
  { id: "test-case-generator", name: "Test Strategy Agent", role: "Scenario & Edge-Case Coverage", description: "Creates comprehensive test scenarios covering happy paths, edge cases, and errors.", pipeline_type: "custom", order: 5, icon: "🧪", estimated_duration: 6, has_skill: true },
  { id: "performance-optimizer", name: "Performance Optimization Agent", role: "Profiling & Bottleneck Analysis", description: "Identifies performance bottlenecks and recommends optimizations for speed.", pipeline_type: "custom", order: 6, icon: "⚡", estimated_duration: 5, has_skill: true },
  { id: "documentation-agent", name: "Documentation Agent", role: "API & Technical Writing", description: "Writes clear documentation including README, API guides, and setup instructions.", pipeline_type: "custom", order: 7, icon: "📚", estimated_duration: 7, has_skill: true },
  { id: "report-generator", name: "Executive Reporting Agent", role: "Insights & Recommendations", description: "Creates executive-ready reports with key metrics, insights, and recommendations.", pipeline_type: "custom", order: 8, icon: "📋", estimated_duration: 5, has_skill: true },
];

export const ALL_LIBRARY_AGENTS: AgentDef[] = [...LIBRARY_AGENTS, ...CUSTOM_AGENTS];

export const PIPELINE_CATEGORIES = [
  { key: "all", label: "All", count: 55 },
  { key: "user_stories", label: "User Stories", count: 6 },
  { key: "ppt", label: "PPT", count: 4 },
  { key: "prototype", label: "Prototype", count: 4 },
  { key: "app_builder", label: "App Builder", count: 15 },
  { key: "mulesoft_to_springboot", label: "Mulesoft → Spring Boot", count: 13 },
  { key: "dotnet_to_azure", label: ".NET → Azure", count: 13 },
  { key: "custom", label: "Custom", count: 8 },
] as const;

export const PIPELINE_COLORS: Record<string, { bg: string; text: string }> = {
  user_stories: { bg: "rgba(79, 195, 247, 0.15)", text: "#4FC3F7" },
  ppt: { bg: "rgba(255, 167, 38, 0.15)", text: "#FFA726" },
  prototype: { bg: "rgba(129, 199, 132, 0.15)", text: "#81C784" },
  app_builder: { bg: "rgba(255, 183, 77, 0.15)", text: "#FFB74D" },
  custom: { bg: "rgba(186, 104, 200, 0.15)", text: "#BA68C8" },
  mulesoft_to_springboot: { bg: "rgba(38, 166, 154, 0.15)", text: "#26A69A" },
  dotnet_to_azure: { bg: "rgba(92, 107, 192, 0.15)", text: "#5C6BC0" },
};
