"""Unit tests for evals.grading.artifacts — the run folder as pure I/O.

Offline only: every test writes into `tmp_path`, no model and no network. Covers
run-id minting and chronological sort, folder creation, prompt hashing, the
append-only guard and `--replace` supersede, and every artifact round-trip.
"""

from __future__ import annotations

import json
from pathlib import Path

import pytest
import yaml

from evals.grading.artifacts import (
    append_stage_run,
    artifact_path,
    compute_system_prompt_hash,
    guard_append_only,
    log_path,
    mark_stale_after,
    new_dataset_run_id,
    read_resolved_config,
    read_run_summary,
    read_stage_artifact,
    read_stage_output,
    read_system_prompt,
    run_folder,
    write_resolved_config,
    write_run_summary,
    write_stage,
    write_system_prompt,
)

TOKEN = "prototype_specify"

REAL_OUTPUT = (
    Path(__file__).resolve().parents[2]
    / "evals"
    / "grading"
    / "model"
    / "workflows"
    / "prototype"
    / "example-run"
    / "artifacts"
    / "prototype_specify_output.json"
)


def make_output(dataset_id: str = "ten-industries") -> dict:
    """A stage output payload in the dataset envelope shape."""
    return {
        "dataset_id": dataset_id,
        "description": "Generated by prototype-specify.",
        "source_agent": "prototype-specify",
        "dataset_run_id": f"260729-083126-{dataset_id}",
        "agent_run_id": f"260729-083126-{dataset_id}-{TOKEN}",
        "rows": [
            {
                "id": "billing_console",
                "industry": "SaaS Billing",
                "tags": ["admin-console"],
                "upstream_precheck_passed": True,
                "upstream_score": 95,
                "prompt": "<spec>...</spec>",
            }
        ],
    }


def assert_dataset_envelope(payload: dict) -> None:
    """The shape any dataset file must satisfy — promoting an output is a copy."""
    assert "dataset_id" in payload
    assert isinstance(payload["rows"], list) and payload["rows"]
    for row in payload["rows"]:
        assert "id" in row
        assert "industry" in row
        assert "prompt" in row


def write_all(run_dir: Path, marker: str = "a") -> None:
    """Write one complete stage so the guard has something to protect."""
    write_stage(
        run_dir,
        TOKEN,
        runs=[{"row_id": "billing_console", "response": marker}],
        grades=[{"row_id": "billing_console", "score": 95}],
        score={"average_all": 95, "marker": marker},
        output=make_output(),
    )


def test_new_dataset_run_id_format():
    """`{YYMMDD-HHMMSS}-{dataset_id}` — timestamp first."""
    run_id = new_dataset_run_id("ten-industries")
    stamp, _, dataset_id = run_id.partition("-")
    assert len(stamp) == 6 and stamp.isdigit()
    assert dataset_id.startswith("-") is False
    assert run_id.endswith("-ten-industries")
    assert len(run_id) == len("260729-083126-") + len("ten-industries")


def test_run_ids_sort_chronologically():
    """Lexicographic sort of minted ids equals chronological order."""
    ids = ["260728-235959-ds", "260729-000001-ds", "260729-083126-ds"]
    assert sorted(reversed(ids)) == ids


def test_run_folder_creates_subdirs(tmp_path):
    """The run folder and its artifacts/prompts/logs subdirs are created."""
    run_dir = run_folder("260729-083126-ten-industries", workflow_dir=tmp_path)
    assert run_dir == tmp_path / ".runs" / "260729-083126-ten-industries"
    for name in ("artifacts", "prompts", "logs"):
        assert (run_dir / name).is_dir()


def test_run_folder_is_idempotent(tmp_path):
    """Calling twice does not raise and does not lose existing content."""
    run_dir = run_folder("260729-083126-ds", workflow_dir=tmp_path)
    (run_dir / "logs" / "keep.log").write_text("x", encoding="utf-8")
    again = run_folder("260729-083126-ds", workflow_dir=tmp_path)
    assert again == run_dir
    assert (run_dir / "logs" / "keep.log").read_text(encoding="utf-8") == "x"


def test_log_path_is_a_row_folder(tmp_path):
    """Logs are `logs/<row_id>/<agent_token>.log` — one brief's transcripts together."""
    run_dir = run_folder("260729-083126-ds", workflow_dir=tmp_path)
    path = log_path(run_dir, TOKEN, "billing_console")
    assert path.name == "prototype_specify.log"
    assert path.parent.name == "billing_console"
    assert path.parent.parent.name == "logs"


def test_system_prompt_hash_format_and_sensitivity():
    """`sha256:<hex>` over the prompt TEXT, changing with the text."""
    first = compute_system_prompt_hash("you are a specify agent")
    assert first.startswith("sha256:")
    assert len(first) == len("sha256:") + 64
    assert first == compute_system_prompt_hash("you are a specify agent")
    assert first != compute_system_prompt_hash("you are a specify agent.")


def test_guard_passes_when_stage_absent(tmp_path):
    """Nothing written yet — the guard is a no-op."""
    run_dir = run_folder("260729-083126-ds", workflow_dir=tmp_path)
    guard_append_only(run_dir, TOKEN, replace=False)


def test_guard_raises_naming_file_and_replace(tmp_path):
    """An existing stage is a hard error naming the file and offering --replace."""
    run_dir = run_folder("260729-083126-ds", workflow_dir=tmp_path)
    write_all(run_dir)
    with pytest.raises(FileExistsError) as excinfo:
        guard_append_only(run_dir, TOKEN, replace=False)
    message = str(excinfo.value)
    assert "prototype_specify_run.json" in message
    assert "--replace" in message


def test_replace_moves_artifacts_into_superseded(tmp_path):
    """`--replace` supersedes all four artifacts as `_a1_*` and clears the slot."""
    run_dir = run_folder("260729-083126-ds", workflow_dir=tmp_path)
    write_all(run_dir, marker="first")
    guard_append_only(run_dir, TOKEN, replace=True)

    superseded = run_dir / "artifacts" / "superseded"
    names = sorted(path.name for path in superseded.glob("*.json"))
    assert names == [
        "prototype_specify_a1_grade.json",
        "prototype_specify_a1_output.json",
        "prototype_specify_a1_run.json",
        "prototype_specify_a1_score.json",
    ]
    assert not artifact_path(run_dir, TOKEN, "run").exists()
    kept = json.loads((superseded / "prototype_specify_a1_score.json").read_text())
    assert kept["marker"] == "first"


def test_replace_increments_and_never_clobbers(tmp_path):
    """A second supersede becomes `_a2_*` and leaves `_a1_*` untouched."""
    run_dir = run_folder("260729-083126-ds", workflow_dir=tmp_path)
    write_all(run_dir, marker="first")
    guard_append_only(run_dir, TOKEN, replace=True)
    write_all(run_dir, marker="second")
    guard_append_only(run_dir, TOKEN, replace=True)

    superseded = run_dir / "artifacts" / "superseded"
    first = json.loads((superseded / "prototype_specify_a1_score.json").read_text())
    second = json.loads((superseded / "prototype_specify_a2_score.json").read_text())
    assert first["marker"] == "first"
    assert second["marker"] == "second"
    assert len(list(superseded.glob("*.json"))) == 8


def test_replace_ignores_other_agents(tmp_path):
    """Superseding one stage leaves another agent's artifacts in place."""
    run_dir = run_folder("260729-083126-ds", workflow_dir=tmp_path)
    write_all(run_dir)
    write_stage(run_dir, "prototype_plan", runs=[], grades=[], score={}, output=make_output())
    guard_append_only(run_dir, TOKEN, replace=True)
    assert artifact_path(run_dir, "prototype_plan", "run").exists()


def test_write_stage_round_trips_all_four(tmp_path):
    """All four artifacts are written and read back unchanged."""
    run_dir = run_folder("260729-083126-ds", workflow_dir=tmp_path)
    write_all(run_dir)
    assert read_stage_artifact(run_dir, TOKEN, "run")[0]["row_id"] == "billing_console"
    assert read_stage_artifact(run_dir, TOKEN, "grade")[0]["score"] == 95
    assert read_stage_artifact(run_dir, TOKEN, "score")["average_all"] == 95
    assert read_stage_output(run_dir, TOKEN) == make_output()


def test_output_matches_dataset_envelope(tmp_path):
    """Promoting an `output.json` to a checked-in dataset is a copy, not a reshape."""
    run_dir = run_folder("260729-083126-ds", workflow_dir=tmp_path)
    write_all(run_dir)
    written = read_stage_output(run_dir, TOKEN)
    assert_dataset_envelope(written)
    assert written["source_agent"] == "prototype-specify"
    assert written["rows"][0]["upstream_precheck_passed"] is True


@pytest.mark.skipif(not REAL_OUTPUT.exists(), reason="the committed example-run fixture is not on disk")
def test_real_example_run_output_matches_same_envelope():
    """The committed example run satisfies the identical shape checks."""
    assert_dataset_envelope(json.loads(REAL_OUTPUT.read_text(encoding="utf-8")))


def test_resolved_config_round_trips_through_yaml(tmp_path):
    """The resolved config is real YAML and reloads to the same dict."""
    run_dir = run_folder("260729-083126-ds", workflow_dir=tmp_path)
    config = {
        "run_id": "prototype-specify-baseline",
        "dataset": "datasets/ten-industries.json",
        "agents": "all",
        "judge": {"provider": "anthropic", "model": "claude-sonnet-5", "threshold": 70},
        "options": {"concurrency": 3, "no_judge": False, "repeats": 1},
    }
    write_resolved_config(run_dir, config)
    path = run_dir / "grade_config.resolved.yaml"
    assert path.exists()
    assert yaml.safe_load(path.read_text(encoding="utf-8")) == config
    assert read_resolved_config(run_dir) == config


def test_read_resolved_config_missing_raises(tmp_path):
    """A run folder with no resolved config fails clearly."""
    run_dir = run_folder("260729-083126-ds", workflow_dir=tmp_path)
    with pytest.raises(FileNotFoundError, match="grade_config.resolved.yaml"):
        read_resolved_config(run_dir)


def test_system_prompt_written_verbatim(tmp_path):
    """The composed prompt is stored byte-for-byte, hash and text agreeing."""
    run_dir = run_folder("260729-083126-ds", workflow_dir=tmp_path)
    prompt = "## Guardrail: agile\n\nYou are a specify agent.\n"
    write_system_prompt(run_dir, TOKEN, prompt)
    path = run_dir / "prompts" / "prototype_specify_system_prompt.md"
    assert path.read_text(encoding="utf-8") == prompt
    assert read_system_prompt(run_dir, TOKEN) == prompt
    assert compute_system_prompt_hash(read_system_prompt(run_dir, TOKEN)) == (
        compute_system_prompt_hash(prompt)
    )


def test_read_system_prompt_missing_raises(tmp_path):
    """A stage with no captured prompt fails clearly."""
    run_dir = run_folder("260729-083126-ds", workflow_dir=tmp_path)
    with pytest.raises(FileNotFoundError, match="system_prompt"):
        read_system_prompt(run_dir, TOKEN)


def test_run_summary_status_transitions(tmp_path):
    """`running` before a stage, rewritten after — the last write wins."""
    run_dir = run_folder("260729-083126-ds", workflow_dir=tmp_path)
    summary = {"dataset_run_id": "260729-083126-ds", "status": "running", "stages": []}
    write_run_summary(run_dir, summary)
    assert read_run_summary(run_dir)["status"] == "running"

    summary["status"] = "completed"
    summary["stages"] = [{"agent_id": "prototype-specify", "status": "completed"}]
    write_run_summary(run_dir, summary)
    reloaded = read_run_summary(run_dir)
    assert reloaded["status"] == "completed"
    assert reloaded["stages"][0]["agent_id"] == "prototype-specify"


def test_stage_runs_is_append_only(tmp_path):
    """Each stage attempt appends an entry; earlier entries survive."""
    run_dir = run_folder("260729-083126-ds", workflow_dir=tmp_path)
    summary = {"status": "running", "stages": []}
    append_stage_run(summary, {"agent_id": "prototype-specify", "attempt": 1})
    write_run_summary(run_dir, summary)

    summary = read_run_summary(run_dir)
    append_stage_run(summary, {"agent_id": "prototype-specify", "attempt": 2})
    write_run_summary(run_dir, summary)

    entries = read_run_summary(run_dir)["stage_runs"]
    assert [entry["attempt"] for entry in entries] == [1, 2]


def test_mark_stale_after_marks_only_later_completed_stages():
    """Re-running a stage makes later completed stages stale, not deleted."""
    summary = {
        "stages": [
            {"agent_id": "prototype-specify", "status": "completed"},
            {"agent_id": "prototype-plan", "status": "completed"},
            {"agent_id": "prototype-analyze", "status": "not_run"},
        ]
    }
    mark_stale_after(summary, "prototype-specify")
    assert [stage["status"] for stage in summary["stages"]] == [
        "completed",
        "stale",
        "not_run",
    ]


def test_mark_stale_after_last_stage_is_a_noop():
    """Re-running the final stage invalidates nothing downstream."""
    summary = {
        "stages": [
            {"agent_id": "prototype-specify", "status": "completed"},
            {"agent_id": "prototype-plan", "status": "completed"},
        ]
    }
    mark_stale_after(summary, "prototype-plan")
    assert [stage["status"] for stage in summary["stages"]] == ["completed", "completed"]


def test_read_missing_stage_output_raises_clearly(tmp_path):
    """A downstream stage asking for an unrun upstream gets a named path."""
    run_dir = run_folder("260729-083126-ds", workflow_dir=tmp_path)
    with pytest.raises(FileNotFoundError) as excinfo:
        read_stage_output(run_dir, "prototype_plan")
    message = str(excinfo.value)
    assert "prototype_plan_output.json" in message
    assert "prototype_plan" in message


def test_read_missing_run_summary_raises_clearly(tmp_path):
    """A crashed run with no summary fails with the path, not a KeyError."""
    run_dir = run_folder("260729-083126-ds", workflow_dir=tmp_path)
    with pytest.raises(FileNotFoundError, match="run_summary.json"):
        read_run_summary(run_dir)
