#!/usr/bin/env python3
"""Regenerate INDEX.md, RULES.md and .cache/* from the cards.

Pure function of the card frontmatter — no LLM, no network, ~instant. Safe to
re-run at any time; it only ever writes the four generated artifacts.

    python3 scripts/knowledge/build_index.py [repo_root]
"""

from __future__ import annotations

import datetime as dt
import sys
from collections import defaultdict
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from cards import (  # type: ignore[import-not-found]  # noqa: E402
    PRIMARY_TYPES,
    SECONDARY_TYPES,
    Card,
    CardError,
    cache_dir,
    frontmatter_hash,
    knowledge_dir,
    load_all,
    read_json,
    repo_root,
    write_json,
)

PACK_VERSION = 1

GENERATED_BANNER = (
    "<!-- GENERATED by scripts/knowledge/build_index.py — do not edit by hand.\n"
    "     Edit the cards under .knowledge/{decisions,fixes,issues,phases}/ and re-run. -->"
)

STATUS_RANK = {"accepted": 0, "proposed": 1, "deprecated": 2, "superseded": 3}


def _sort_key(c: Card):
    """Newest first within a type, falling back to id for undated cards."""
    return (c.date or "0000-00-00", c.id)


def _areas(c: Card) -> str:
    return ",".join(c.area) if c.area else "-"


def render_catalog(cards: list[Card], built: str) -> str:
    """Everything migrated for completeness but too voluminous to always load.

    Not part of the session prime. `ctx.py` searches these the same as any other
    card; this file exists so a human can scan what was migrated.
    """
    by_type: dict[str, list[Card]] = defaultdict(list)
    for c in cards:
        if c.type in SECONDARY_TYPES:
            by_type[c.type].append(c)
    total = sum(len(v) for v in by_type.values())
    out = [
        GENERATED_BANNER, "", "# Catalog", "",
        f"{total} cards · built {built}", "",
        "Migrated for completeness — **not** loaded by default. Search with",
        "`ctx.py \"<terms>\"`; these rank alongside fixes and decisions.", "",
    ]
    titles = {"bug": "QA bugs", "test": "Test suites", "req": "Requirements",
              "doc": "Documents", "task": "Work folders"}
    for typ in SECONDARY_TYPES:
        group = sorted(by_type.get(typ, []), key=lambda c: c.id)
        if not group:
            continue
        out += [f"## {titles[typ]} ({len(group)})", ""]
        for c in group:
            out.append(f"{c.id} [{_areas(c)}] {c.summary}")
        out.append("")
    return "\n".join(out).rstrip() + "\n"


def render_index(cards: list[Card], built: str) -> str:
    by_type: dict[str, list[Card]] = defaultdict(list)
    for c in cards:
        if c.type in PRIMARY_TYPES:
            by_type[c.type].append(c)

    rules = [c for c in by_type.get("decision", []) if c.status != "superseded"]
    counts = (
        f"{len(cards)} cards · rules {len(rules)} · fixes {len(by_type.get('fix', []))} "
        f"· issues {len(by_type.get('issue', []))} · phases {len(by_type.get('phase', []))}"
    )

    out = [
        GENERATED_BANNER,
        "",
        "# Knowledge Index",
        "",
        f"{counts} · built {built}",
        "",
        "This index is the *only* thing that needs loading. Never read a register whole.",
        "Fetch a card body with `ctx.py --show <ID>`; search with `ctx.py \"<terms>\"`.",
        "",
    ]

    sections = [
        ("decision", "Rules in force"),
        ("fix", "Fixes"),
        ("issue", "Issues"),
        ("phase", "Phases"),
    ]
    for typ, title in sections:
        group = sorted(by_type.get(typ, []), key=_sort_key, reverse=(typ != "decision"))
        if typ == "decision":
            group = sorted(group, key=lambda c: (STATUS_RANK.get(c.status, 9), c.id))
        if not group:
            continue
        out.append(f"## {title} ({len(group)})")
        out.append("")
        for c in group:
            if typ == "decision":
                flag = "" if c.status == "accepted" else f" ({c.status})"
                out.append(f"{c.id} [{_areas(c)}]{flag} {c.summary}")
            else:
                out.append(f"{c.id} {c.date or '-'} [{_areas(c)}] {c.summary}")
        out.append("")

    return "\n".join(out).rstrip() + "\n"


def render_rules(cards: list[Card], built: str) -> str:
    rules = [c for c in cards if c.type == "decision" and c.status in ("accepted", "proposed")]
    rules.sort(key=lambda c: (STATUS_RANK.get(c.status, 9), c.id))

    out = [
        GENERATED_BANNER,
        "",
        "# Rules in force",
        "",
        f"{len(rules)} decisions · built {built}",
        "",
        "These constrain new work. A change that contradicts one of these is a defect,",
        "not a preference — either follow it or supersede the decision explicitly.",
        "",
    ]

    by_area: dict[str, list[Card]] = defaultdict(list)
    for c in rules:
        for a in c.area or ["general"]:
            by_area[a].append(c)

    for area in sorted(by_area):
        out.append(f"## {area}")
        out.append("")
        for c in by_area[area]:
            flag = "" if c.status == "accepted" else f" **[{c.status}]**"
            out.append(f"- **{c.id}**{flag} — {c.summary}")
            if c.list_field("enforced_by"):
                out.append(f"  - enforced by: {', '.join(c.list_field('enforced_by'))}")
        out.append("")

    if not rules:
        out.append("_No decisions recorded yet._")
        out.append("")

    return "\n".join(out).rstrip() + "\n"


def build_links(cards: list[Card]) -> dict:
    by_file: dict[str, list[str]] = defaultdict(list)
    by_area: dict[str, list[str]] = defaultdict(list)
    edges: dict[str, list[str]] = {}
    rules_by_file: dict[str, list[str]] = defaultdict(list)

    for c in cards:
        for f in c.files:
            by_file[f].append(c.id)
            if c.type == "decision" and c.status == "accepted":
                rules_by_file[f].append(c.id)
        for a in c.area:
            by_area[a].append(c.id)
        links = c.links()
        if links:
            edges[c.id] = sorted(set(links))

    # reverse edges, so `relates:` only has to be written once
    back: dict[str, set[str]] = defaultdict(set)
    for src, dsts in edges.items():
        for d in dsts:
            back[d].add(src)

    return {
        "by_file": {k: sorted(set(v)) for k, v in sorted(by_file.items())},
        "by_area": {k: sorted(set(v)) for k, v in sorted(by_area.items())},
        "rules_by_file": {k: sorted(set(v)) for k, v in sorted(rules_by_file.items())},
        "edges": {k: edges[k] for k in sorted(edges)},
        "backlinks": {k: sorted(v) for k, v in sorted(back.items())},
    }


def main(argv: list[str]) -> int:
    root = Path(argv[1]).resolve() if len(argv) > 1 else repo_root()
    kdir = knowledge_dir(root)
    if not kdir.is_dir():
        print(f"error: no .knowledge/ directory at {kdir}", file=sys.stderr)
        return 2

    try:
        cards = load_all(root)
    except CardError as e:
        print(f"error: {e}", file=sys.stderr)
        return 1

    dupes = {c.id for c in cards if sum(1 for o in cards if o.id == c.id) > 1}
    if dupes:
        print(f"error: duplicate card ids: {', '.join(sorted(dupes))}", file=sys.stderr)
        return 1

    built = dt.datetime.now().strftime("%Y-%m-%d %H:%M")

    sdir = cache_dir(root)          # .knowledge/surface — everything below is generated
    sdir.mkdir(parents=True, exist_ok=True)
    (sdir / "INDEX.md").write_text(render_index(cards, built), encoding="utf-8")
    (sdir / "RULES.md").write_text(render_rules(cards, built), encoding="utf-8")
    (sdir / "CATALOG.md").write_text(render_catalog(cards, built), encoding="utf-8")

    cdir = sdir
    entries = [c.to_dict() for c in sorted(cards, key=lambda c: c.id)]
    # Wrapped, not a bare list: `facets` lets a tool offer filters without reading
    # all 536 entries, and `counts` answers "how many X" in one lookup.
    facets: dict[str, dict[str, int]] = {"type": {}, "status": {}, "area": {}}
    for e in entries:
        facets["type"][e["type"]] = facets["type"].get(e["type"], 0) + 1
        if e.get("status"):
            facets["status"][e["status"]] = facets["status"].get(e["status"], 0) + 1
        for a in e.get("area", []):
            facets["area"][a] = facets["area"].get(a, 0) + 1
    write_json(
        cdir / "index.json",
        {
            "generated": built,
            "count": len(entries),
            "facets": {k: dict(sorted(v.items(), key=lambda kv: -kv[1])) for k, v in facets.items()},
            "fields": ["id", "type", "status", "date", "area", "files", "summary", "source", "path"],
            "entries": entries,
        },
    )
    write_json(cdir / "links.json", build_links(cards))

    counts: dict[str, int] = defaultdict(int)
    for c in cards:
        counts[c.type] += 1

    write_json(
        cdir / "stamp.json",
        {
            "pack_version": PACK_VERSION,
            "built_at": built,
            "card_count": len(cards),
            "counts": dict(sorted(counts.items())),
            "frontmatter_sha1": frontmatter_hash(cards),
            "sources": read_json(kdir / "sources.json", {}),
        },
    )

    # Surfaces quote card counts and recent entries, so they are only correct
    # immediately after an index build. Regenerate them here rather than trusting
    # anyone to remember.
    for mod in ("build_surface", "build_architecture"):
        try:
            gen = __import__(mod)
            gen.main([f"{mod}.py", str(root)])
        except Exception as e:  # never let surface generation break the index
            print(f"warning: {mod} failed: {e}", file=sys.stderr)

    idx_kb = (sdir / "INDEX.md").stat().st_size / 1024
    rules_kb = (sdir / "RULES.md").stat().st_size / 1024
    print(
        f"built {len(cards)} cards "
        f"({', '.join(f'{k} {v}' for k, v in sorted(counts.items()))}) · "
        f"INDEX.md {idx_kb:.1f} KB + RULES.md {rules_kb:.1f} KB "
        f"≈ {int((idx_kb + rules_kb) * 1024 / 4):,} tokens"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
