#!/usr/bin/env python3
"""Generate the single entry point: .knowledge/surface/ENTRY.md

There used to be one surface file per gated register — nine near-identical stubs
saying the same thing about different files. The register you asked for is already
named in the read-gate's `additionalContext`, so the file itself does not need to
vary. One entry point, and `type` is a field you filter on.

    python3 scripts/knowledge/build_surface.py

Called automatically from build_index.py; the counts here come from the cards, so
it is only correct immediately after an index build.
"""

from __future__ import annotations

import sys
from collections import Counter
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from cards import load_all, repo_root, surface_dir  # type: ignore[import-not-found]  # noqa: E402

TYPE_DESC = {
    "decision": ("rules in force — always loaded", 'ctx.py --rules sse'),
    "fix":      ("shipped fixes, symptom + cause", 'ctx.py "reconnect banner"'),
    "issue":    ("tracked issues", 'ctx.py --type issue "review gate"'),
    "bug":      ("QA campaign bugs", 'ctx.py --type bug "resume"'),
    "phase":    ("phase pointers → _register-parts/ shards", 'ctx.py --type phase "compiler"'),
    "test":     ("test-register sections", 'ctx.py --type test "compiler"'),
    "req":      ("requirement sections", 'ctx.py --type req "artifacts"'),
    "doc":      ("pointers to planning documents", 'ctx.py --type doc "roadmap"'),
    "task":     ("pointers to quick/ and phases/ work folders", 'ctx.py --type task "resume"'),
}

PRIMARY = ("decision", "fix", "issue", "phase")


def main(argv: list[str]) -> int:
    root = Path(argv[1]).resolve() if len(argv) > 1 else repo_root()
    sdir = surface_dir(root)
    sdir.mkdir(parents=True, exist_ok=True)

    cards = load_all(root)
    counts = Counter(c.type for c in cards)
    areas = Counter(a for c in cards for a in c.area)
    planning_kb = sum(
        p.stat().st_size for p in (root / ".planning").rglob("*") if p.is_file()
    ) / 1024

    lines = [
        "<!-- GENERATED by scripts/knowledge/build_surface.py — do not edit. -->",
        "",
        "# Project knowledge — entry point",
        "",
        f"You were redirected here because you asked to read a `.planning/` register "
        f"whole. All {planning_kb / 1024:.1f} MB of `.planning/` is carried as "
        f"**{len(cards)} cards** in `.knowledge/cards/`; the registers themselves are "
        "unchanged on disk.",
        "",
        "This is not a failure. Query below — do not retry the original path.",
        "",
        "## Query",
        "",
        "```bash",
        'python3 scripts/knowledge/ctx.py "<symptom words>"       # search everything',
        "python3 scripts/knowledge/ctx.py --for <file>            # rules + history for a file",
        "python3 scripts/knowledge/ctx.py --rules <area>          # rules in force",
        "python3 scripts/knowledge/ctx.py --show <ID>             # one card, full prose",
        "```",
        "",
        "`--for` before editing a file is the cheapest way to find the rule you are "
        "about to break.",
        "",
        "## Where the project is",
        "",
        "`.knowledge/surface/ARCHITECTURE.md` — the milestone and phase in flight, the "
        "boundaries CI enforces, the workflows registered, and the ADRs in force. It is "
        "the only file here about the present; read it before planning anything.",
        "",
        "## Types",
        "",
        "| type | n | what it is | example |",
        "|---|---:|---|---|",
    ]
    for t, (desc, ex) in TYPE_DESC.items():
        if counts.get(t):
            lines.append(f"| `{t}` | {counts[t]} | {desc} | `{ex}` |")

    top_areas = ", ".join(f"`{a}` ({n})" for a, n in areas.most_common(10))
    lines += [
        "",
        f"**Areas:** {top_areas}",
        "",
        "## Full lists",
        "",
        "| file | holds | load |",
        "|---|---|---|",
        "| `.knowledge/surface/ARCHITECTURE.md` | **current state** — milestone, phase, "
        "enforced boundaries, ADRs in force | **first** |",
        "| `.knowledge/INVARIANTS.md` | project-wide constraints | always |",
        "| `.knowledge/surface/RULES.md` | decisions in force | always |",
        f"| `.knowledge/surface/INDEX.md` | {sum(counts[t] for t in PRIMARY)} primary cards "
        f"({', '.join(PRIMARY)}) | always |",
        f"| `.knowledge/surface/CATALOG.md` | {len(cards) - sum(counts[t] for t in PRIMARY)} "
        "secondary cards (bug, test, req, doc, task) | on demand |",
        "| `.knowledge/surface/index.json` | every entry + `facets` for filtering | tools only |",
        "",
        "## If you genuinely need the raw register",
        "",
        "Re-read it with a `limit`/`offset`, or include `READ_REGISTER_ANYWAY` in the "
        "command. Reading one whole is what this store exists to avoid — the largest "
        "is ~960 KB, about 240 K tokens.",
    ]

    out = sdir / "ENTRY.md"
    out.write_text("\n".join(lines) + "\n", encoding="utf-8")

    # Remove the per-register stubs this replaces.
    old = sdir / "registers"
    removed = 0
    if old.is_dir():
        for f in old.glob("*.md"):
            f.unlink()
            removed += 1
        old.rmdir()

    note = f" (removed {removed} per-register stubs)" if removed else ""
    print(f"surface: ENTRY.md {out.stat().st_size / 1024:.1f} KB{note}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
