"""The store as a single file: .knowledge/records.jsonl

One JSON object per line, one line per record. Replaces 536 individual card files.

**Bodies are not stored.** They already exist, verbatim, in `.planning/` — copying
them into cards duplicated 870 KB for no gain, since nothing reads a body until it
is explicitly asked for. Each record keeps a `source` anchor instead, and
`resolve_body()` extracts the section on demand.

That makes `.planning/` load-bearing: delete a register and its bodies go with it.
`compact.py --materialize` writes every body back out first, so that decision stays
reversible.

Why JSONL rather than one big markdown file: a markdown store re-creates the
original problem — anything that opens it gets everything. JSONL is line-addressable,
appendable, and diffs one line per change.
"""

from __future__ import annotations

import json
import re
from pathlib import Path

RECORDS_NAME = "records.jsonl"

# Field order in the serialized line. Stable order keeps diffs readable and makes
# the frontmatter hash deterministic.
FIELD_ORDER = (
    "id", "type", "status", "date", "area", "files", "summary", "source",
    "ticket", "severity", "campaign", "invariants", "covers", "covers_total",
    "relates", "produces", "supersedes", "derived_from", "enforced_by",
    "collision_of", "duplicate_rows", "no_table_row", "shard", "size",
    "status_detail", "y",
)


def records_path(kdir: Path) -> Path:
    return kdir / RECORDS_NAME


def load_records(kdir: Path) -> list[dict]:
    p = records_path(kdir)
    if not p.is_file():
        return []
    out = []
    for n, line in enumerate(p.read_text(encoding="utf-8").splitlines(), 1):
        line = line.strip()
        if not line or line.startswith("//"):
            continue
        try:
            out.append(json.loads(line))
        except json.JSONDecodeError as e:
            raise ValueError(f"{p}:{n}: malformed record — {e}") from None
    return out


def dump_record(rec: dict) -> str:
    ordered = {k: rec[k] for k in FIELD_ORDER if k in rec and rec[k] not in (None, "", [])}
    ordered.update({k: v for k, v in rec.items() if k not in FIELD_ORDER and v not in (None, "", [])})
    return json.dumps(ordered, ensure_ascii=False, sort_keys=False)


def save_records(kdir: Path, recs: list[dict]) -> None:
    kdir.mkdir(parents=True, exist_ok=True)
    recs = sorted(recs, key=lambda r: (r.get("type", ""), r.get("id", "")))
    header = (
        "// .knowledge/records.jsonl — the knowledge store. One record per line.\n"
        "// Generated by extract.py / migrate.py; regenerate views with build_index.py.\n"
        "// Bodies are NOT stored here; they resolve from `source` on demand.\n"
    )
    records_path(kdir).write_text(
        header + "\n".join(dump_record(r) for r in recs) + "\n", encoding="utf-8"
    )


# --------------------------------------------------------------------- body lookup


def _section_after(text: str, pattern: re.Pattern, stop: re.Pattern) -> str | None:
    m = pattern.search(text)
    if not m:
        return None
    tail = text[m.start() :]
    nxt = stop.search(tail, 1)
    return (tail[: nxt.start()] if nxt else tail).rstrip()


def resolve_body(rec: dict, root: Path) -> str:
    """Fetch a record's prose from its source, on demand.

    Returns a plain-language explanation rather than raising when the source has
    moved — a missing body is information, not a crash.
    """
    src = str(rec.get("source", ""))
    if not src:
        return "_No source recorded for this record._"
    path = src.split("#")[0]
    p = root / path

    if not p.exists():
        return f"_Source `{path}` no longer exists. This record's prose cannot be recovered._"

    if p.is_dir():
        members = sorted(q for q in p.rglob("*") if q.is_file())
        listing = "\n".join(f"- `{q.relative_to(root).as_posix()}`" for q in members[:40])
        more = f"\n\n_(+{len(members) - 40} more files)_" if len(members) > 40 else ""
        return f"Work folder `{path}` — {len(members)} files.\n\n{listing}{more}"

    if p.suffix not in (".md", ".txt", ".json", ".yaml", ".yml"):
        return f"Binary or non-text artifact at `{path}` ({p.stat().st_size / 1024:.0f} KB)."

    text = p.read_text(encoding="utf-8", errors="replace")
    rid = str(rec.get("id", ""))
    # Collision suffixes and campaign suffixes are card-store inventions; the
    # register only knows the base id.
    base = rec.get("collision_of") or re.sub(r"(-sse|-resume|-custom-workflow)$", "", rid)
    base = re.sub(r"^((?:FIX|ISS|BUG|CWF)-[\w.]*?\d)[a-z]$", r"\1", base)

    stop_h = re.compile(r"(?m)^#{2,4} ")
    for pat in (
        re.compile(rf"(?m)^#{{2,4}} +{re.escape(base)}\b"),          # detail section
        re.compile(rf"(?m)^#{{2,4}} +{re.escape(rid)}\b"),
    ):
        got = _section_after(text, pat, stop_h)
        if got:
            return got

    # Table-row entries: return every row for this id.
    rows = re.findall(rf"(?m)^\|\s*{re.escape(base)}\s*\|.*$", text)
    if rows:
        return "Register rows:\n\n" + "\n".join(rows)

    # Sectioned docs (tests, requirements) anchor on the heading slug.
    anchor = src.split("#", 1)[1] if "#" in src else ""
    if anchor:
        words = [w for w in anchor.split("-") if len(w) > 3][:4]
        for m in re.finditer(r"(?m)^### +(.+)$", text):
            head = m.group(1).lower()
            if words and all(w in head for w in words):
                got = _section_after(text, re.compile(rf"(?m)^### +{re.escape(m.group(1))}$"), stop_h)
                if got:
                    return got

    return (
        f"_Could not locate `{rid}` inside `{path}`. The register may have been "
        f"restructured; open it directly with a `limit` to check._"
    )
