variable "expected_account_id" {
  description = "AWS account ID this bootstrap must run against. Leave blank to auto-adopt the account the AWS CLI / Terraform provider is currently authenticated to (the live `aws sts get-caller-identity` account). Set to a concrete 12-digit id to make the guard abort plan/apply on any mismatch — recommended for shared / multi-account org setups."
  type        = string
  default     = ""

  validation {
    condition     = var.expected_account_id == "" || can(regex("^[0-9]{12}$", var.expected_account_id))
    error_message = "expected_account_id must be empty (auto-detect) or a 12-digit AWS account ID."
  }
}

variable "aws_region" {
  description = "AWS region for the state bucket and lock table."
  type        = string
  default     = "eu-central-1"

  validation {
    condition     = can(regex("^[a-z]{2}-[a-z]+-[0-9]$", var.aws_region))
    error_message = "aws_region must look like e.g. eu-central-1."
  }
}

variable "owner" {
  description = "Tag value for Owner. Drives AWS Cost Explorer / Billing reports filtered by tag — finance can answer 'how much is team X costing us?' when this is set. Default 'velocityai' is fine for single-team / single-project accounts; override for multi-team / multi-project accounts where per-team cost allocation matters."
  type        = string
  default     = "velocityai"
}

variable "cost_center" {
  description = "Tag value for CostCenter (finance code). Same Cost-Explorer reasoning as `owner`; default 'velocityai' is the catch-all. Set to your org's real finance code (e.g. 'UKI-AI-001') when you want this stack's spend to roll up into a specific budget."
  type        = string
  default     = "velocityai"
}

variable "state_bucket_name" {
  description = "Globally-unique S3 bucket name for the Terraform state. Suggested: velocityai-tfstate-<region> (e.g. velocityai-tfstate-eu-central-1). NOTE: S3 bucket names are globally unique across ALL AWS accounts, so pick a name unlikely to collide; the region suffix helps but is not a guarantee."
  type        = string

  validation {
    condition     = length(var.state_bucket_name) >= 3 && length(var.state_bucket_name) <= 63
    error_message = "S3 bucket names must be 3-63 chars."
  }
}

variable "lock_table_name" {
  description = "DynamoDB table name for Terraform state locking."
  type        = string
  default     = "velocityai-tfstate-locks"
}

# --- CI/CD runners (Option B: full per-env isolation) -----------------------

variable "create_gitlab_runner" {
  description = "Create the GitLab connection + per-env CodeBuild project(s). Required for the CI/CD pipeline (infra/buildspec.yml); set true and supply gitlab_repo_url + runners. Default false keeps a state-backend-only bootstrap."
  type        = bool
  default     = false
}

variable "gitlab_repo_url" {
  description = "HTTPS clone URL of the GitLab repo for the CodeBuild runner, e.g. https://gitlab.com/<group>/<project>.git. Only used when create_gitlab_runner = true."
  type        = string
  default     = ""

  validation {
    condition     = var.gitlab_repo_url == "" || can(regex("^https://.*\\.git$", var.gitlab_repo_url))
    error_message = "gitlab_repo_url must be an https://... .git clone URL (or empty when the runner is disabled)."
  }
}

variable "deploy_permissions_boundary_arn" {
  description = "Optional IAM permissions-boundary ARN attached to every per-env CodeBuild deploy role. RECOMMENDED in a shared account: scope it to velocityai-* so even the broad ProvisionStack statement cannot touch non-project resources. Empty = no boundary."
  type        = string
  default     = ""
}

variable "runners" {
  description = <<-EOT
    Per-environment GitLab CI/CD runner definitions, keyed by environment name
    (dev|stage|prod). Each entry creates one fully isolated CodeBuild runner +
    deploy role + webhook + log group. `branch` is the git branch (or, for tag/
    release triggers, the name used to derive the project name — keep stable).
    The non-secret per-env config (cors_origins, bedrock model, alert_email) is
    injected into foundation/app as TF_VAR_*; secrets (SECRET_KEY, DB password)
    are auto-generated by the foundation secrets module and never pass through
    here. `extra_env` is the seam for adding per-env build vars without code
    changes.
  EOT
  type = map(object({
    branch                       = string
    cors_origins                 = string
    bedrock_model_id             = string
    bedrock_inference_profile_id = string
    alert_email                  = string
    compute_type                 = optional(string, "BUILD_GENERAL1_MEDIUM")
    log_retention_days           = optional(number, 30)
    extra_env                    = optional(map(string), {})
    # How this env's build is triggered:
    #   "branch" (default) -> push to `branch`
    #   "tag"              -> a git tag push matching `tag_pattern`
    #   "release"          -> a GitLab Release create/update (any release)
    trigger_type = optional(string, "branch")
    # Tag-name pattern for "tag" runners only (matched after refs/tags/; do NOT
    # add your own ^ or $). Empty = ANY tag.
    tag_pattern = optional(string, "")
  }))
  default = {}

  validation {
    condition     = alltrue([for env in keys(var.runners) : contains(["dev", "stage", "prod"], env)])
    error_message = "runners keys must be one of: dev, stage, prod (matching the foundation/app environment name)."
  }
  validation {
    condition     = alltrue([for r in values(var.runners) : length(trimspace(r.branch)) > 0])
    error_message = "each runner's branch must be a non-empty branch name."
  }
  validation {
    condition     = alltrue([for r in values(var.runners) : r.cors_origins != "*"])
    error_message = "cors_origins must be a concrete origin list, never '*'."
  }
  validation {
    condition     = alltrue([for r in values(var.runners) : can(regex("^[^@]+@[^@]+\\.[^@]+$", r.alert_email))])
    error_message = "each runner's alert_email must look like a valid email address."
  }
  validation {
    condition     = alltrue([for r in values(var.runners) : contains(["BUILD_GENERAL1_SMALL", "BUILD_GENERAL1_MEDIUM", "BUILD_GENERAL1_LARGE", "BUILD_GENERAL1_2XLARGE"], r.compute_type)])
    error_message = "compute_type must be a valid CodeBuild compute type (e.g. BUILD_GENERAL1_MEDIUM)."
  }
  validation {
    condition     = alltrue([for r in values(var.runners) : contains(["branch", "tag", "release"], r.trigger_type)])
    error_message = "each runner's trigger_type must be \"branch\", \"tag\", or \"release\"."
  }
}
