# =============================================================================
# VelocityAI App Layer (per environment) — the deployable unit
# =============================================================================
# Everything that changes when you ship: the EC2 instance + data EBS volume +
# EIP, the public DNS record, the docker-compose.yml + image-tag deploy object
# in S3 (driven by var.image_tag), the CloudWatch monitoring, and the Resource
# Groups. Long-lived base (network, KMS, IAM, secrets, backups) is read from
# the foundation layer via terraform_remote_state (see data.tf / locals.tf).
#
# State key: velocityai/<env>/app.tfstate
# Apply order: bootstrap -> shared -> foundation(<env>) -> app(<env>)
# =============================================================================

# --- Account / region guard -------------------------------------------------
# The app layer applies independently of foundation, so it runs its own guard
# (and sources account_id/region/partition from it) rather than trusting the
# provider blindly.
module "account_guard" {
  source = "../modules/account_guard"

  expected_account_id = var.expected_account_id
  expected_region     = var.aws_region
}

# --- Compute (EC2, data EBS, EIP) ------------------------------------------
module "compute" {
  source = "../modules/compute"

  name_prefix               = local.name_prefix
  environment               = var.environment
  region                    = module.account_guard.region
  instance_type             = var.instance_type
  subnet_id                 = local.fnd.public_subnet_id
  availability_zone         = local.fnd.availability_zone
  security_group_id         = local.fnd.app_security_group_id
  iam_instance_profile_name = local.fnd.instance_profile_name
  kms_key_arn               = local.fnd.kms_key_arn
  ssh_key_name              = var.ssh_key_name
  root_volume_size_gb       = var.root_volume_size_gb
  data_volume_size_gb       = var.data_volume_size_gb

  # Console/API guard against an accidental terminate/stop. Flip to false in
  # tfvars + apply to deliberately roll the instance.
  disable_api_termination = var.disable_api_termination
  disable_api_stop        = var.disable_api_stop

  # Environment threaded into the on-host bootstrap. The image tag is NOT here
  # (it lives in the deploy-env S3 object below, re-read at every redeploy);
  # user_data has ignore_changes so a tag bump never replaces the instance.
  user_data_extra_env = {
    VELOCITYAI_BACKUP_BUCKET = local.fnd.backup_bucket_name
    VELOCITYAI_PARAM_PREFIX  = local.fnd.parameter_path_prefix
    VELOCITYAI_KMS_KEY_ID    = local.fnd.kms_key_arn
    VELOCITYAI_FQDN          = module.dns.fqdn
    VELOCITYAI_ECR_REGISTRY  = local.registry
    VELOCITYAI_GIT_REF       = var.git_ref
    VELOCITYAI_ACME_EMAIL    = var.alert_email
  }
}

# --- DNS --------------------------------------------------------------------
module "dns" {
  source = "../modules/dns"

  name_prefix       = local.name_prefix
  use_nip_io        = var.use_nip_io
  route53_zone_name = var.route53_zone_name
  app_subdomain     = var.app_subdomain
  eip_address       = module.compute.public_ip
  ttl_seconds       = var.dns_ttl_seconds
}

# --- docker-compose.yml hosted in S3 ---------------------------------------
# The on-host bootstrap downloads this to run `docker compose pull && up -d`.
# `source_hash` makes Terraform re-upload when the local file changes.
resource "aws_s3_object" "compose_yaml" {
  bucket = local.fnd.backup_bucket_name
  key    = "config/docker-compose.yml"

  source      = "${path.root}/../../../docker-compose.yml"
  source_hash = filemd5("${path.root}/../../../docker-compose.yml")

  content_type           = "text/yaml"
  server_side_encryption = "aws:kms"
  kms_key_id             = local.fnd.kms_key_arn

  tags = {
    Name      = "${local.name_prefix}-compose-yaml"
    Component = "compute"
  }
}

# --- Deploy env (image tag) hosted in S3 -----------------------------------
# This is what makes the app layer the "deployable unit": the resolved image
# URIs for var.image_tag. Changing image_tag changes this object's content, so
# `app apply` re-uploads it and the on-host redeploy (SSM RunCommand in
# infra/buildspec.yml) reads it to `docker compose pull` the new tag. The
# docker-compose.yml interpolates ${BACKEND_IMAGE}/${FRONTEND_IMAGE} from here.
resource "aws_s3_object" "deploy_env" {
  bucket = local.fnd.backup_bucket_name
  key    = "config/deploy.env"

  content = <<-EOT
    # Generated by Terraform (app layer). Do not edit by hand.
    IMAGE_TAG=${var.image_tag}
    BACKEND_IMAGE=${local.backend_image}
    FRONTEND_IMAGE=${local.frontend_image}
  EOT

  content_type           = "text/plain"
  server_side_encryption = "aws:kms"
  kms_key_id             = local.fnd.kms_key_arn

  tags = {
    Name      = "${local.name_prefix}-deploy-env"
    Component = "compute"
  }
}

# --- Monitoring -------------------------------------------------------------
module "monitoring" {
  source = "../modules/monitoring"

  providers = {
    aws         = aws
    aws.useast1 = aws.useast1
  }

  name_prefix                 = local.name_prefix
  environment                 = var.environment
  instance_id                 = module.compute.instance_id
  kms_key_arn                 = local.fnd.kms_key_arn
  alert_email                 = var.alert_email
  log_retention_days          = var.log_retention_days
  log_retention_overrides     = var.log_retention_overrides
  billing_alarm_threshold_usd = var.billing_alarm_threshold_usd
  bedrock_model_id            = local.effective_model_id
  cw_metric_namespace         = "VelocityAI/${title(var.environment)}"
  backup_vault_name           = local.fnd.backup_vault_name

  bedrock_daily_token_threshold        = var.bedrock_daily_token_threshold
  bedrock_throttles_threshold          = var.bedrock_throttles_threshold
  bedrock_throttles_evaluation_periods = var.bedrock_throttles_evaluation_periods
  agent_error_rate_threshold           = var.agent_error_rate_threshold
  stuck_workflows_threshold            = var.stuck_workflows_threshold
  stuck_workflows_check_period         = var.stuck_workflows_check_period

  # CloudTrail management-event audit-trail wiring (C2-1).
  instance_role_arn       = local.fnd.instance_role_arn
  secrets_path_prefix_arn = local.secrets_path_prefix_arn
  project_cmk_arn         = local.fnd.kms_key_arn
}

# --- Resource Groups (tag-query everything in this env) --------------------
module "resourcegroups" {
  source = "../modules/resourcegroups"

  name_prefix = local.name_prefix
  environment = var.environment
}
