### Admin - List users
GET {{apiRoot}}/api/admin/users
Authorization: Bearer {{jwt}}

### Admin - Update user tier
PATCH {{apiRoot}}/api/admin/users/{{userId}}/tier
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
	"tier": "pro"
}

### Admin - Create user
POST {{apiRoot}}/api/admin/users
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
	"email": "new-user@example.com",
	"password": "StrongPass123!",
	"tier": "basic",
	"is_admin": false
}

### Admin - Delete user
DELETE {{apiRoot}}/api/admin/users/{{userId}}
Authorization: Bearer {{jwt}}
